[package]
name = "syscalls"
version = "0.0.0"
edition = "2018"

[lib]
path = "lib.rs"

[features]
native = []

[dependencies]
stack_dst = { path = "../../../externals/crates.io/stack_dst", default-features = false }
kernel = { path = "../../Core" }
gui = { path = "../gui" }

