[package]
name = "network"
version = "0.0.0"
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
kernel = { path = "../../Core" }
stack_dst = { path = "../../../externals/crates.io/stack_dst", default-features = false }
shared_map = { path = "../shared_map" }

