[package]
name = "filebrowser"
version = "0.0.1"
edition = "2015"

[dependencies]
wtk = { path = "../libwtk" }
vec_ring = { path = "../libvec_ring" }

std = { path = "../libstd" }
syscalls = { path = "../libsyscalls" }
loader = { path = "../loader/lib" }
