[package]
name = "fs_ext_n"
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
kernel = { path = "../../Core" }
vfs = { path = "../vfs" }
block_cache = { path = "../block_cache" }
kernel_derives = { path = "../../kernel_derives" }
