[package]
name = "handle_server-bin"
version = "0.0.1"
edition = "2015"

[dependencies]
handle_server = { path = "../libhandle_server" }

# Sysroot crates
std = { path = "../libstd" }
syscalls = { path = "../libsyscalls" }
loader = { path = "../loader/lib" }

