[package]
name = "std_rt"
version = "0.0.1"
edition = "2015"

[lib]
path = "lib.rs"

[dependencies]
syscalls = { path = "../libsyscalls" }
macros = { path = "../libmacros" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(arch, values("native"))'] }

