[package]
name = "login"
version = "0.0.1"
edition = "2015"

[dependencies]
wtk = { path = "../libwtk" }
async = { path = "../libasync" }
lazy_static = { path = "../liblazy_static" }

std = { path = "../libstd" }
syscalls = { path = "../libsyscalls" }
loader = { path = "../loader/lib" }
