[package]
name = "storage-ahci"
version = "0.0.0"
edition = "2015"

[lib]
path = "lib.rs"

[dependencies]
kernel = { path = "../../Core" }
storage-ata = { path = "../storage_ata" }
storage-scsi = { path = "../storage_scsi" }
